= Begriffe und Definitionen
:toc:
:sectnums:
:stem:

== Grundbegriffe

=== Spurweite

Die Spurweite ist der minimale lichte Abstand zwischen den Innenkanten der Schienenköpfe.

=== Radlast

Die Radlast ist die auf ein einzelnes Rad wirkende statische Vertikalkraft.

[NOTE]
====
Die Radlast ist die Leitgröße für die Klassifizierung, nicht die Fahrzeuggesamtmasse.
====

=== Achslast

Die Achslast ist die Summe der Radlasten der Räder einer Achse.

=== Bemessungsradlast

Die Bemessungsradlast ist die dynamisch erhöhte Radlast zur Auslegung von Gleis und Fahrzeug.

[NOTE]
====
Berechnung und Anwendung siehe <<04_lastmodell.adoc#,Lastmodell>>.
====

== Fahrzeugbegriffe

=== Fester Achsstand

Der feste Achsstand ist der Abstand zwischen dem äußersten Radsatz am vorderen und hinteren Ende eines starren Fahrwerks.

[IMPORTANT]
====
Der feste Achsstand begrenzt direkt den befahrbaren Mindestradius.
====

=== Adhäsionsmasse

Die Adhäsionsmasse ist jener Teil der Lokomotivmasse, der auf angetriebenen Achsen lastet und für die Kraftübertragung verfügbar ist.

=== Schwerpunkthöhe

Die Schwerpunkthöhe ist der vertikale Abstand des Gesamtschwerpunkts zur Schienenoberkante.

== Gleisbegriffe

=== Mindestradius

Der Mindestradius ist der kleinste zulässige Gleisbogenradius, gemessen als Gleisachsradius (Mitte zwischen den Schienen), für eine gegebene Fahrzeug-/Strecken-Kombination.

=== Überhöhung

Die Überhöhung ist die vertikale Differenz zwischen äußerer und innerer Schiene im Gleisbogen.

=== Längsneigung

Die Längsneigung ist die Steigung oder das Gefälle der Gleistrasse in Fahrtrichtung, angegeben in Prozent (%).

=== Unterbau

Der Unterbau umfasst alle tragenden Schichten unterhalb der Schwellen (Bettung, Tragschicht, Planum).

== Betriebsbegriffe

=== Streckenklasse

Die Streckenklasse ist die Kombination aus Lastklasse, Geschwindigkeitsklasse und Betriebsart.

[NOTE]
====
Definition und Klassifikation siehe <<03_klassensysteme.adoc#,Klassensysteme>>.
====

=== Zulässige Geschwindigkeit

Die zulässige Geschwindigkeit ist die maximale Fahrgeschwindigkeit an einem bestimmten Streckenabschnitt unter Berücksichtigung aller limitierenden Faktoren.

=== Dynamikfaktor

Der Dynamikfaktor stem:[\varphi(V)] ist ein geschwindigkeitsabhängiger Multiplikator zur Berechnung der dynamischen Lasterhöhung.

[NOTE]
====
Definition und Werte siehe <<04_lastmodell.adoc#,Lastmodell>>.
====

== Sicherheitsbegriffe

=== Designfall

Der Designfall ist das ungünstigste, aber betrieblich zu erwartende Szenario (z. B. nasse Schienen, maximale Last, volle Geschwindigkeit).

[NOTE]
====
Optimale oder ideale Bedingungen sind *kein* Designfall.
====

=== Haftreibungszahl

Die Haftreibungszahl stem:[\mu_{design}] ist der für die Auslegung anzusetzende Wert der Reibung zwischen Rad und Schiene.

== Klassenbegriffe

[[lastklasse]]
=== Lastklasse (L)

Kategorisierung nach zulässigen Rad- und Achslasten.

[[geschwindigkeitsklasse]]
=== Geschwindigkeitsklasse (V)

Kategorisierung nach zulässiger Geschwindigkeit und dynamischer Beanspruchung.

[[betriebsart]]
=== Betriebsart (B)

Kategorisierung nach Sicherheitsniveau und Nutzungsart.

[NOTE]
====
Klassenwerte und Anforderungen siehe <<03_klassensysteme.adoc#,Klassensysteme>>.
====
