ifndef::sbo-header-loaded[]
include::../common-header.adoc[]
endif::[]

= Lastannahmen und Bemessung
[abstract]
Dieses Kapitel definiert die Lastannahmen und Bemessungsgrundlagen für Gleis, Unterbau und Fahrzeuge. Es beschreibt die anzusetzenden statischen und dynamischen Lasten sowie die maßgebenden Designfälle.

== Zweck und Anwendungsbereich

Die Lastannahmen dienen der einheitlichen und nachvollziehbaren Bemessung von:

* Gleisanlagen
* Oberbau und Unterbau
* Fahrzeugrahmen und Fahrwerken
* Sonderbauwerken (z. B. Weichen, Übergänge)

Dieses Kapitel gilt für alle Betriebsarten (BG, BA, BP) und alle Lastklassen (L1–L3).

== Maßgebende Lastgröße

Maßgebend für alle Bemessungen ist die *Radlast*.

Begründung:

* Lasten werden punktuell über das Rad in die Schiene eingeleitet
* Lokale Überlasten treten auf Radebene auf
* Achslast und Fahrzeugmasse sind abgeleitete Größen

Definitionen:

* *Radlast Q*: Vertikale Kraft eines einzelnen Rades auf das Gleis
* *Achslast A*: Summe der Radlasten einer Achse (normal stem:[A = 2 Q])

== Statische Lastannahmen

=== Fahrzeug- und Nutzlasten

Die statische Radlast ergibt sich aus:

* Eigenmasse des Fahrzeugs
* Maximale Nutzlast
* Lastverteilung auf die Achsen
* Anzahl der Räder

Die Berechnung MUSS für den ungünstigsten Lastzustand erfolgen, einschließlich:

* maximaler Zuladung
* ungünstiger Schwerpunktlage
* asymmetrischer Beladung (innerhalb realistischer Grenzen)

=== Gleichmäßige und ungleichmäßige Lastverteilung

Eine gleichmäßige Lastverteilung DARF nur angenommen werden, wenn:

* die Bauart des Fahrzeugs dies erzwingt, oder
* entsprechende konstruktive Maßnahmen vorhanden sind

In allen anderen Fällen MUSS eine ungleichmäßige Lastverteilung berücksichtigt werden.

==== Berechnung bei gleichmäßiger Lastverteilung

Für ein symmetrisch beladenes Fahrzeug mit gleichmäßiger Achslastverteilung:

[stem]
++++
Q_"stat" = (m_"Fzg" * g) / n_"Räder"
++++

Wobei:

* stem:[m_"Fzg"] – Fahrzeugmasse [kg]
* stem:[g] – Erdbeschleunigung (9,81 m/s²)
* stem:[n_"Räder"] – Anzahl der Räder

==== Berechnung bei ungleichmäßiger Lastverteilung

Bei ungleichmäßiger Lastverteilung (z. B. Tender, Drehgestelle, einseitige Beladung):

*Methode 1: Berechnung nach Hebelgesetz*

Bei bekannter Schwerpunktlage und Achsabständen:

[stem]
++++
Q_"max" = (m_"Fzg" * g * l_"Hebel") / (n_"Achsen" * l_"Achsabstand" * n_"Räder/Achse")
++++

*Methode 2: Worst-Case-Annahme*

Wenn die tatsächliche Lastverteilung unbekannt ist, MUSS angenommen werden:

[stem]
++++
Q_"max" = (m_"Fzg" * g * f_"Ungl") / n_"Räder"
++++

Wobei stem:[f_"Ungl"] ein Ungleichverteilungsfaktor ist (typisch 1,3–1,5).

== Dynamische Zusatzlasten

=== Allgemeines

Im Betrieb treten zusätzliche dynamische Beanspruchungen auf durch:

* Gleisunebenheiten
* Setzungen des Unterbaus
* Schienenstöße und Übergänge
* Anfahr- und Bremsvorgänge
* Fahrdynamik in Bögen

Diese Effekte werden durch einen geschwindigkeitsabhängigen Dynamikfaktor stem:[phi(V)] pauschal berücksichtigt.

=== Dynamikfaktoren

Für die Ermittlung der dynamischen Radlasten sind folgende Faktoren anzusetzen:

[cols="2,1"]
|===
| Geschwindigkeitsklasse | Dynamikfaktor φ

| V3 (≤ {v3-max} km/h)
| {v3-phi}

| V2 (≤ {v2-max} km/h)
| {v2-phi}

| V1 (≤ {v1-max} km/h)
| {v1-phi}
|===

Die dynamische Radlast ergibt sich aus:

[stem]
++++
Q_"dyn" = Q_"stat" * phi
++++

== Einrad-Überlast (lokale Unregelmäßigkeiten)

Zusätzlich zu den dynamischen Zusatzlasten ist zu berücksichtigen, dass lokale Unregelmäßigkeiten auftreten können, z. B.:

* Setzungen einzelner Schwellen
* Steine oder Fremdkörper im Gleis
* Übergänge zwischen Bauabschnitten

Für diese Fälle ist anzunehmen, dass ein einzelnes Rad kurzzeitig eine erhöhte Last aufnimmt.

Die maßgebende lokale Radlast ergibt sich aus:

[stem]
++++
Q_"lokal" = max(Q_"dyn", 1.6 * Q_"stat")
++++

Wobei:

* stem:[Q_"lokal"] – maßgebende Radlast für lokale Nachweise (Schiene, Schwelle, Unterbau)
* stem:[Q_"dyn"] – dynamische Radlast aus Geschwindigkeitsklasse (siehe oben)
* stem:[Q_"stat"] – statische Radlast
* Faktor 1,6 – repräsentiert lokale Überlasten infolge Setzung und Gleisunruhe

Diese Last ist bei der Auslegung von Schiene, Schwelle, Bettung und Untergrund maßgebend zu berücksichtigen.

[IMPORTANT]
====
Die Einrad-Überlast ist maßgebend für:

* Schwellendimensionierung
* Unterbaubemessung
* Schienenbruchrisiko
====

== Designfälle

=== Allgemeiner Designfall

Die Bemessung MUSS für die ungünstigste, aber betrieblich zu erwartende Kombination erfolgen:

* Maximale statische Radlast
* Höchste zulässige Geschwindigkeit
* Nasser oder verschmutzter Zustand
* Verschleißbedingter Zustand der Komponenten

=== Designfälle im Personenverkehr (BP)

Für Personenverkehr sind zusätzliche Designfälle anzusetzen:

* Vollbesetzung der Fahrzeuge
* Maximale zulässige Geschwindigkeit
* Notbremsung im Gefälle
* Ungünstige Schwerpunktlage

Diese Designfälle sind unabhängig von regulären Güter- oder Arbeitsfahrten zu betrachten.

== Punktlastige und besondere Lasten

=== Punktlastige Ladung

Ladungen mit stark konzentrierter Masse (z. B. Maschinen, Motoren, Steinblöcke) erfordern eine gesonderte Betrachtung.

Auch bei geringer Gesamtmasse kann eine unzulässig hohe Radlast entstehen.

Punktlastige Ladung DARF nur transportiert werden, wenn die resultierende Radlast innerhalb der zulässigen Lastklasse liegt.

=== Sondertransporte

Lasten oberhalb der regulären Lastklasse dürfen nur als Sondertransport erfolgen.

Sondertransporte erfordern mindestens:

* Reduzierte Geschwindigkeit (mindestens V3)
* Definierte Strecke
* Dokumentation und Nachweisführung

== Seitenkräfte

=== Entstehung

In Kurven wirken Seitenkräfte auf Schiene und Unterbau:

[stem]
++++
F_"Seite" = (m * v^2) / r
++++

Wobei:

* stem:[m] – Fahrzeugmasse
* stem:[v] – Geschwindigkeit
* stem:[r] – Kurvenradius

=== Berücksichtigung

Seitenkräfte erhöhen die Belastung der äußeren Schiene und begrenzen:

* Zulässige Geschwindigkeit in Kurven
* Mindestradius für gegebene Geschwindigkeit
* Stabilität schmaler Unterbauten

Weitere Anforderungen ergeben sich aus Kapitel <<04_gleisgeometrie.adoc#,Gleisgeometrie und Trassierung>>.

[NOTE]
====
Für Personenverkehr (BP) MUSS die Querbeschleunigung begrenzt werden (Komfort, Kippgefahr).
====

== Längskräfte

=== Anfahren

Beim Anfahren wirken Zugkräfte:

[stem]
++++
F_"Zug" = m * a + m * g * s + F_"Roll"
++++

Wobei:

* stem:[a] – Beschleunigung
* stem:[s] – Längsneigung [‰]
* stem:[F_"Roll"] – Rollwiderstand

=== Bremsen

Beim Bremsen wirken Bremskräfte auf Schiene und Schwellen.

[IMPORTANT]
====
Die Bremskraft ist durch die Haftreibung begrenzt:

[stem]
++++
F_("Brems,max") = mu * m * g
++++
====

Die tatsächlich verfügbare Bremskraft KANN unterhalb dieses Grenzwertes liegen.

== Stoßlasten

=== Kuppelstoß

Beim Rangieren oder Ankuppeln entstehen kurzzeitige Stoßlasten.

[NOTE]
====
Kuppelstöße sind für die Gleisbemessung in der Regel nicht maßgebend, wohl aber für Fahrzeugkonstruktion.
====

=== Entgleisung (Grenzfall)

Im Fall einer Entgleisung KANN ein Rad auf die Schwelle aufsetzen.

[IMPORTANT]
====
Schwellen MÜSSEN diese Punktlast ohne Bruch aufnehmen können (Rückfallsicherheit).
====

== Bemessungsgrundsatz

[IMPORTANT]
====
Die Bemessung erfolgt stets auf Basis der *maßgebenden Radlast*.

Wenn mehrere Lastannahmen relevant sind, ist die jeweils ungünstigste anzusetzen.
====

== Anwendung in der Bemessung

=== Schienenbemessung

[stem]
++++
sigma_"Schiene" = f(Q_"dyn", "Schwellenabstand", "Schienenträgheitsmoment")
++++

=== Schwellenbemessung

[stem]
++++
sigma_"Schwelle" = f(Q_"lokal", "Schwellenbreite", "Bettungsmodul")
++++

=== Unterbaubemessung

[stem]
++++
p_"Unterbau" = (Q_"lokal") / (A_"Lastverteilung")
++++

Die Lastverteilung erfolgt unter 45°-Winkel durch die Bettung.

== Abgrenzung

Dieses Kapitel behandelt ausschließlich Lastannahmen und Bemessungsgrundlagen.

Weitere Einschränkungen ergeben sich insbesondere aus:

* Gleisgeometrie
* Längsneigung und Haftung
* Bremsvermögen
* Betriebsart (insbesondere BP)
