ifndef::sbo-header-loaded[]
include::../common-header.adoc[]
endif::[]

= Personenverkehr (Klasse P)

[abstract]
Dieses Kapitel definiert die verschärften Anforderungen für Personenverkehr (Betriebsart BP).

[IMPORTANT]
====
Anlagen und Fahrzeuge, die für Personenverkehr genutzt werden, MÜSSEN explizit dafür zugelassen werden. Eine Zulassung für Güterverkehr ist nicht ausreichend.
====

== Zusätzliche Sicherheitsanforderungen

// TODO(#63): Inhalt ausarbeiten
_Platzhalter: Redundante Bremssysteme, Notausstiege, Sicherheitsgurte, Brandschutz_

== Zulässige Geschwindigkeiten

// TODO(#66): Inhalt ausarbeiten
_Platzhalter: Reduzierte V_max-Werte gegenüber Güterverkehr, Kurven- und Gefälle-Limits_

== Bremsanforderungen

// TODO(#67): Inhalt ausarbeiten
_Platzhalter: Höhere Bremsvermögen, Redundanz, Notbremseinrichtung für Fahrgäste_

== Fahrzeuge und Einrichtungen

// TODO(#65): Inhalt ausarbeiten
_Platzhalter: Sitze, Türen, Haltegriffe, Beleuchtung, Kommunikation_

== Streckenfreigabe für Personenverkehr

// TODO(#72): Inhalt ausarbeiten
_Platzhalter: Abnahmeverfahren, Dokumentation, regelmäßige Prüfungen, Zuständigkeiten_
