ifndef::sbo-header-loaded[]
include::../common-header.adoc[]
endif::[]

= Personenverkehr (Klasse P)

[abstract]
Dieses Kapitel definiert die verschärften Anforderungen für Personenverkehr (Betriebsart BP).

[IMPORTANT]
====
Anlagen und Fahrzeuge, die für Personenverkehr genutzt werden, MÜSSEN explizit dafür zugelassen werden. Eine Zulassung für Güterverkehr ist nicht ausreichend.
====

== Zusätzliche Sicherheitsanforderungen

// TODO: Inhalt ausarbeiten - siehe https://github.com/Nebensound/SBO/issues/13
_Platzhalter: Redundante Bremssysteme, Notausstiege, Sicherheitsgurte, Brandschutz_

== Zulässige Geschwindigkeiten

// TODO: Inhalt ausarbeiten - siehe https://github.com/Nebensound/SBO/issues/13
_Platzhalter: Reduzierte V_max-Werte gegenüber Güterverkehr, Kurven- und Gefälle-Limits_

== Bremsanforderungen

// TODO: Inhalt ausarbeiten - siehe https://github.com/Nebensound/SBO/issues/13
_Platzhalter: Höhere Bremsvermögen, Redundanz, Notbremseinrichtung für Fahrgäste_

== Fahrzeuge und Einrichtungen

// TODO: Inhalt ausarbeiten - siehe https://github.com/Nebensound/SBO/issues/13
_Platzhalter: Sitze, Türen, Haltegriffe, Beleuchtung, Kommunikation_

== Streckenfreigabe für Personenverkehr

// TODO: Inhalt ausarbeiten - siehe https://github.com/Nebensound/SBO/issues/13
_Platzhalter: Abnahmeverfahren, Dokumentation, regelmäßige Prüfungen, Zuständigkeiten_
