ifndef::sbo-header-loaded[]
include::../common-header.adoc[]
endif::[]

= Prüfung, Wartung und Instandhaltung

[abstract]
Dieses Kapitel definiert Prüfintervalle, Prüfmethoden, Verschleißgrenzen und Dokumentationspflichten.

== Prüfintervalle

// TODO: Inhalt ausarbeiten - siehe https://github.com/Nebensound/SBO/issues/11
_Platzhalter: Tägliche, wöchentliche, monatliche, jährliche Prüfungen; Abhängigkeit von Betriebsintensität_

== Sicht- und Maßprüfungen

// TODO: Inhalt ausarbeiten - siehe https://github.com/Nebensound/SBO/issues/11
_Platzhalter: Sichtprüfung auf Schäden, Vermessung von Spurweite, Überhöhung, Verwindung_

== Verschleißgrenzen

// TODO: Inhalt ausarbeiten - siehe https://github.com/Nebensound/SBO/issues/11
_Platzhalter: Schienenverschleiß, Radverschleiß, Schwellenzustand_

== Dokumentation

// TODO: Inhalt ausarbeiten - siehe https://github.com/Nebensound/SBO/issues/11
_Platzhalter: Prüfprotokolle, Wartungsbücher, digitale Erfassung_

== Maßnahmen bei Abweichungen

// TODO: Inhalt ausarbeiten - siehe https://github.com/Nebensound/SBO/issues/11
_Platzhalter: Sofortmaßnahmen, Geschwindigkeitsreduzierung, Streckensperrung, Instandsetzungsfristen_
