ifndef::sbo-header-loaded[]
include::../common-header.adoc[]
endif::[]

= Sonderfälle und Abweichungen

[abstract]
Dieses Kapitel behandelt Sonderfälle, provisorische Gleise, Baustellenbetrieb und temporäre Abweichungen von den Standardanforderungen.

== Provisorische Gleise

// TODO: Inhalt ausarbeiten - siehe https://github.com/Nebensound/SBO/issues/10
_Platzhalter: Temporäre Gleisanlagen, reduzierte Anforderungen, zeitliche Begrenzung_

== Baustellenbetrieb

// TODO: Inhalt ausarbeiten - siehe https://github.com/Nebensound/SBO/issues/10
_Platzhalter: Betrieb während Baumaßnahmen, Geschwindigkeitslimits, Sicherungsmaßnahmen_

== Temporäre Last- oder Geschwindigkeitsänderungen

// TODO: Inhalt ausarbeiten - siehe https://github.com/Nebensound/SBO/issues/10
_Platzhalter: Verfahren zur befristeten Änderung von Betriebsparametern, Dokumentation_

== Betrieb unter eingeschränkten Bedingungen

// TODO: Inhalt ausarbeiten - siehe https://github.com/Nebensound/SBO/issues/10
_Platzhalter: Notbetrieb, eingeschränkte Sicht, besondere Witterungsbedingungen_
